export const language = [
  { eng: "Messages", arab: "رسائل" },
  { eng: "Settings", arab: "إعدادات" },
  { eng: "Create\nEvent", arab: "انشاء \nحدث " },
  { eng: "Profile", arab: "الملف \nالشخصي" },
  { eng: "Events", arab: "الأحداث" },
  { eng: "Search", arab: "بحث" },
  { eng: "Your Account", arab: "الحساب الخاص بك" },
  { eng: "Notifications", arab: "إشعارات" },
  { eng: "Accessibility", arab: "إمكانية الوصول" },
  { eng: "Privacy", arab: "خصوصية" },
  { eng: "Help", arab: "يساعد" },
  { eng: "About", arab: "حول" },
  { eng: "Language Changed Successfully", arab: "تم تغيير اللغة بنجاح" },
  { eng: "Change Language", arab: "تغيير اللغة" },
  { eng: "Select language", arab: "اختار اللغة" },
  { eng: "Cancel", arab: "يلغي" },
  { eng: "Apply", arab: "تطبيق" },
  { eng: "Logout", arab: "تسجيل خروج" },
  { eng: "Change Password", arab: "تغيير كلمة المرور" },
  { eng: "Change Username", arab: "غير اسم المستخدم" },
  { eng: "Name", arab: "اسم" },
  { eng: "Desc", arab: "تنازلي" },
  { eng: "Date", arab: "تاريخ" },
  { eng: "Private", arab: "خاص" },
  { eng: "Public", arab: "عام" },
  { eng: "Set", arab: "تعيين" },
];
